title: KO-LAB Home space
description: "The home of KO-LAB"
author:
  name: "create_people"
  email: "info@ko-lab.space"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Creative_People"
year : "2019"
